# -------------- LANGUAGE SPECIFIC BLOCK

title: Pisma iz Sarajeva

url: "https://pismaizsarajeva.com" # the base hostname & protocol for your site, e.g. http://example.com

metaDescription: >-
  Početak rata u Bosni.
  Desetogodišnji Kosta sa majkom i mlađim bratom napušta Sarajevo.
  Otac ostaje u opsednutom, bombardovanom gradu i zajedno sa ostalim Sarajlijama preživljava teške dane.
  Uprkos tome, sinovima šalje šaljiva pisma, želeći da ih razveseli i ohrabri.
  Desetak godina kasnije, koristeći autentična očeva pisma, Kosta sastavlja priču svog detinjstva."

metaImage: pisma-iz-sarajeva.jpg

firstLetterLink: "/sr/prvo-pismo"
firstLetterText: "Prvo pismo"

prevLinkText: Prethodno pismo
nextLinkText: Sledeće pismo

homeLinkText: Početna strana

aboutText: O knjizi i sajtu
aboutLink: /sr/o-knjizi-i-sajtu

footerText: U znak sećanja na Kostu, Beograd 2020.

collections:
  sr:
    output: true
    permalink: /sr/:name/

# -------------- END OF LANGUAGE SPECIFIC BLOCK

baseurl: "" # the subpath of your site, e.g. /blog

# Exclude from processing.
exclude:
  # - _en # LANGUAGE SPECIFIC
  - _assets
  - .cache
  - node_modules
  - package-lock.json
  - package.json
  - .editorconfig
  - Gemfile.lock
  - Gemfile
  - README.md
  - english
  - .browserlistrc
  - .gitignore
  - .nvmrc

plugins:
  - jekyll-redirect-from

# Plugins which are activated by default on GitHub pages

# - jekyll-coffeescript
# - jekyll-gist
# - jekyll-github-metadata
# - jekyll-relative-links
# - jekyll-optional-front-matter
# - jekyll-readme-index
# - jekyll-default-layout
# - jekyll-titles-from-headings

# Plugins allowed by GitHub Pages

# - jekyll-coffeescript
# - jekyll-feed
# - jekyll-gist
# - jekyll-github-metadata
# - jekyll-paginate
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
# - jekyll-avatar
# - jemoji
# - jekyll-mentions
# - jekyll-relative-links
# - jekyll-optional-front-matter
# - jekyll-readme-index
# - jekyll-default-layout
# - jekyll-titles-from-headings
# - jekyll-include-cache
# - jekyll-octicons
