languages:
  - link: https://lettersfromsarajevo.com/
    text: English
    flag: gb.svg
  - link: https://lettersfromsarajevo.com/ru/
    text: Русский
    flag: ru.svg
  - link: https://lettersfromsarajevo.com/pt-br/
    text: Português do Brasil
    flag: br.svg
  # - link: https://lettersfromsarajevo.com/cn/
  #   text: 中文
  #   flag: cn.svg
  - link: https://pismaizsarajeva.com/
    text: Srpski
    flag: sr.svg

baseurl: ""

# Exclude from processing.
exclude:
  - sr
  - _assets
  - .cache
  - node_modules
  - package-lock.json
  - package.json
  - .editorconfig
  - Gemfile.lock
  - Gemfile
  - README.md
  - english
  - .browserlistrc
  - .gitignore
  - .nvmrc
  - build-serbian.sh

plugins:
  - jekyll-redirect-from

# Plugins which are activated by default on GitHub pages

# - jekyll-coffeescript
# - jekyll-gist
# - jekyll-github-metadata
# - jekyll-relative-links
# - jekyll-optional-front-matter
# - jekyll-readme-index
# - jekyll-default-layout
# - jekyll-titles-from-headings

# Plugins allowed by GitHub Pages

# - jekyll-coffeescript
# - jekyll-feed
# - jekyll-gist
# - jekyll-github-metadata
# - jekyll-paginate
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
# - jekyll-avatar
# - jemoji
# - jekyll-mentions
# - jekyll-relative-links
# - jekyll-optional-front-matter
# - jekyll-readme-index
# - jekyll-default-layout
# - jekyll-titles-from-headings
# - jekyll-include-cache
# - jekyll-octicons
