# -------------- LANGUAGE SPECIFIC BLOCK

title: Cartas de Sarajevo

url: "https://cartasdesarajevo.com.br" # the base hostname & protocol for your site, e.g. http://example.com

metaDescription: >-
  O começo da Guerra da Bósnia.
  Kosta, um garoto de dez anos, foge de Sarajevo com sua mãe e irmão mais novo. Seu pai fica na cidade, sitiada e bombardeada, sobrevivendo a tempos difíceis com outros sarajevanos. Apesar de tudo, ele escreve cartas divertidas para seus filhos, tentando encorajá-los e animá-los.
  Dez anos depois, usando as cartas originais escritas por seu pai, Kosta escreve a história de sua infância.

metaImage: letters-from-sarajevo.jpg

firstLetterLink: "/ptbr/letter-one"
firstLetterText: "Primeira carta"

prevLinkText: Carta anterior
nextLinkText: Próxima carta

homeLinkText: Home page

aboutText: Sobre o livro e o website
aboutLink: /ptbr/about

footerText: "Em memória de Kosta, Belgrado 2020."
footerCopyright: Todo o conteúdo e o código desse site está disponível sob a licença <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>.

analyticsCode: UA-65023927-5

languages:
  - link: https://lettersfromsarajevo.com
    text: English
  - link: https://pismaizsarajeva.com
    text: Srpski

collections:
  ptbr:
    output: true
    permalink: /ptbr/:name/

# -------------- END OF LANGUAGE SPECIFIC BLOCK

baseurl: "" # the subpath of your site, e.g. /blog

# Exclude from processing.
exclude:
  - _sr # language specific
  - _assets
  - .cache
  - node_modules
  - package-lock.json
  - package.json
  - .editorconfig
  - Gemfile.lock
  - Gemfile
  - README.md
  - english
  - .browserlistrc
  - .gitignore
  - .nvmrc
  - english.sh

plugins:
  - jekyll-redirect-from
# Plugins which are activated by default on GitHub pages

# - jekyll-coffeescript
# - jekyll-gist
# - jekyll-github-metadata
# - jekyll-relative-links
# - jekyll-optional-front-matter
# - jekyll-readme-index
# - jekyll-default-layout
# - jekyll-titles-from-headings

# Plugins allowed by GitHub Pages

# - jekyll-coffeescript
# - jekyll-feed
# - jekyll-gist
# - jekyll-github-metadata
# - jekyll-paginate
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
# - jekyll-avatar
# - jemoji
# - jekyll-mentions
# - jekyll-relative-links
# - jekyll-optional-front-matter
# - jekyll-readme-index
# - jekyll-default-layout
# - jekyll-titles-from-headings
# - jekyll-include-cache
# - jekyll-octicons
