# -------------- LANGUAGE SPECIFIC BLOCK

title: Letters from Sarajevo

url: "https://lettersfromsarajevo.com" # the base hostname & protocol for your site, e.g. http://example.com

metaDescription: >-
  The beginning of the Bosnian war.
  Ten-year-old Kosta flees Sarajevo, together with his mother and his younger brother.
  His father stays in the besieged and bombarded city.
  In spite of everything, he writes funny letters to his sons, trying to cheer them up.
  Ten years later, using authentic letters written by his father, Kosta writes the story of his childhood.

metaImage: letters-from-sarajevo.jpg

firstLetterLink: "/en/letter-one"
firstLetterText: "Letter one"

prevLinkText: Previous letter
nextLinkText: Next letter

homeLinkText: Home page

aboutText: About the book and the website
aboutLink: /en/about

footerText: In loving memory of Kosta, Belgrade 2020.
footerCopyright: All of the content and site's code are under <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a> license.

# analyticsCode:

collections:
  en:
    output: true
    permalink: /en/:name/

# -------------- END OF LANGUAGE SPECIFIC BLOCK

baseurl: "" # the subpath of your site, e.g. /blog

# Exclude from processing.
exclude:
  - _sr # language specific
  - _assets
  - .cache
  - node_modules
  - package-lock.json
  - package.json
  - .editorconfig
  - Gemfile.lock
  - Gemfile
  - README.md
  - english
  - .browserlistrc
  - .gitignore
  - .nvmrc
  - english.sh

plugins:
  - jekyll-redirect-from

# Plugins which are activated by default on GitHub pages

# - jekyll-coffeescript
# - jekyll-gist
# - jekyll-github-metadata
# - jekyll-relative-links
# - jekyll-optional-front-matter
# - jekyll-readme-index
# - jekyll-default-layout
# - jekyll-titles-from-headings

# Plugins allowed by GitHub Pages

# - jekyll-coffeescript
# - jekyll-feed
# - jekyll-gist
# - jekyll-github-metadata
# - jekyll-paginate
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
# - jekyll-avatar
# - jemoji
# - jekyll-mentions
# - jekyll-relative-links
# - jekyll-optional-front-matter
# - jekyll-readme-index
# - jekyll-default-layout
# - jekyll-titles-from-headings
# - jekyll-include-cache
# - jekyll-octicons
